const invalidPostApi = [
    { field: 'nome', value: '1234.to_i', code: 400 },
    { field: 'nome', value: '1234.to_f', code: 400 },
    { field: 'nome', value: 'nulo', code: 400 },
    { field: 'nome', value: 'number_negative', code: 400 },
    { field: 'nome', value: 'boolean_true', code: 400 },
    { field: 'nome', value: 'boolean_false', code: 400 },
    { field: 'nome', value: '256.characters_type_string', code: 201 },
    { field: 'nome', value: '256.characters_type_numbers', code: 400 },
    { field: 'nome', value: 'Array', code: 400 },
    { field: 'nome', value: 'Hash', code: 400 },
    { field: 'email', value: '1234.to_i', code: 400 },
    { field: 'email', value: '1234.to_f', code: 400 },
    { field: 'email', value: 'nulo', code: 400 },
    { field: 'email', value: 'number_negative', code: 400 },
    { field: 'email', value: 'boolean_true', code: 400 },
    { field: 'email', value: 'boolean_false', code: 400 },
    { field: 'email', value: '256.characters_type_string', code: 400 },
    { field: 'email', value: '256.characters_type_numbers', code: 400 },
    { field: 'email', value: 'Array', code: 400 },
    { field: 'email', value: 'Hash', code: 400 },
    { field: 'password', value: '1234.to_i', code: 400 },
    { field: 'password', value: '1234.to_f', code: 400 },
    { field: 'password', value: 'nulo', code: 400 },
    { field: 'password', value: 'number_negative', code: 400 },
    { field: 'password', value: 'boolean_true', code: 400 },
    { field: 'password', value: 'boolean_false', code: 400 },
    { field: 'password', value: '256.characters_type_string', code: 400 },
    { field: 'password', value: '256.characters_type_numbers', code: 400 },
    { field: 'password', value: 'Array', code: 400 },
    { field: 'password', value: 'Hash', code: 400 },
    { field: 'administrador', value: '1234.to_i', code: 400 },
    { field: 'administrador', value: '1234.to_f', code: 400 },
    { field: 'administrador', value: 'nulo', code: 400 },
    { field: 'administrador', value: 'number_negative', code: 400 },
    { field: 'administrador', value: 'boolean_true', code: 400 },
    { field: 'administrador', value: 'boolean_false', code: 400 },
    { field: 'administrador', value: '256.characters_type_string', code: 400 },
    { field: 'administrador', value: '256.characters_type_numbers', code: 400 },
    { field: 'administrador', value: 'Array', code: 400 },
    { field: 'administrador', value: 'Hash', code: 400 },
];

export default invalidPostApi;